# litellm configuration file template
## load key from environment variables: os.environ/<ENV-VAR> # runs os.getenv('ENV-VAR')
# supported models and providers
## - https://models.litellm.ai/
## - https://docs.litellm.ai/docs/providers


#environment_variables: {}


model_list:
  - model_name: str  # received model name
    litellm_params:  # all params for litellm
      model: str  # model name for litellm
      api_base: str  # base url
      api_key: os.environ/API_KEY  # os.getenv('API_KEY')
      rpm: int  # [OPTIONAL] rate limit
      tpm: int  # [OPTIONAL] rate limit
      api_version: ''
#    model_info:
#      id: string
#      mode: embedding
#      input_cost_per_token: 0
#      output_cost_per_token: 0
#      max_tokens: 2048
#      base_model: gpt-4-1106-preview
#      additionalProp1: {}


# if for default model
#  - model_name: "*"
#    litellm_params:
#      model: ''


litellm_settings:
  drop_params: True
  num_retries: int  # retry call model_name
  request_timeout: int  # Timeout error
  allowed_fails: int  # cooldown
#  success_callback: ['']


# settings for the litellm proxy server
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
#  routing_strategy: Literal["simple-shuffle", "least-busy", "usage-based-routing","latency-based-routing"], default="simple-shuffle"
#  model_group_alias: dict
#  num_retries: int
#  timeout: int
#  alerting: ['']

